//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildlifeMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Species
    {
        public int ID { get; set; }
        [Display(Name = "English Name")]
        public string EnglishName { get; set; }
        [Display(Name = "Latin Name")]
        public string LatinName { get; set; }
        [Display(Name = "Summary")]
        public string ShortDescription { get; set; }
        [Display(Name = "Description")]
        public string LongDescription { get; set; }
        public string ImageURL { get; set; }
        public string VideoURL { get; set; }
    }
}
